module RDF
  class ORA < RDF::Vocabulary("http://vocab.ox.ac.uk/ora#")
    property :DataSteward
    property :DataStorageAgreement
    property :TitularAgent
    property :affiliation
    property :agreementStatus
    property :agreementType
    property :annotation
    property :apcPaid
    property :author
    property :copyrightNote
    property :dateCollected
    property :dataContributor
    property :dataSteward
    property :dataStorageDetails
    property :dataStorageSilo
    property :digitalSize
    property :digitalSizeAllocated
    property :embargoStatus
    property :embargoStart
    property :embargoEnd
    property :embargoReason
    property :embargoRelease
    property :examiner
    property :hadCreationActivity
    property :hadPublicationActivity
    property :hadTitularActivity
    property :hasAgreement
    property :hasDataset
    property :hasDataManagementPlan
    property :hasInvoice
    property :isPartOfSeries
    property :locator
    property :monetaryValue
    property :monetaryStatus
    property :oaReason
    property :oaStatus
    property :refException
    property :reviewStatus
    property :rightsHolderGroup
    property :storageAgreement
    property :supervisor
    property :thesisDegreeLevel
  end
end
