module RDF
  class PSO < RDF::Vocabulary("http://purl.org/spar/pso/")
    property :"accepted-for-publication"
    property :"anonymized"
    property :"APC-fully-waived"
    property :"APC-not-charged"
    property :"APC-not-required"
    property :"APC-paid"
    property :"APC-partially-waived"
    property :archived
    property :catalogued
    property :"closed-access"
    property :"confidential"
    property :"copy-edited"
    property :corrected
    property :draft
    property :embargoed
    property :enhanced
    property :"final-draft"
    property :"gold-open-access"
    property :"gratis-open-access"
    property :"green-open-access"
    property :"in-press"
    property :"initial-draft"
    property :"intermediate-draft"
    property :"libre-open-access"
    property :"non-confidential"
    property :"open-access"
    property :"peer-reviewed"
    property :proof
    property :published
    property :"rejected-for-publication"
    property :republished
    property :"restricted-access"
    property :"retracted-from-publication"
    property :"reviewed"
    property :"revised"
    property :"submitted"
    property :"subscription-access"
    property :"under-review"
    property :unpublished
    property :"version-of-record"
    property :"withdrawn-from-submission"
    property :holdsStatusInTime
    property :isAcquiredAsConsequenceOf
    property :isLostAsConsequenceOf
    property :isStatusHeldBy
    property :isStatusIn
    property :resultsInAcquiring
    property :resultsInLosing
    property :withStatus
    property :PublicationStatus
    property :Status
    property :StatusInTime
  end
end
