development:
  username: sandbox_user
  password: sandbox
  host: http://10.0.0.173/
  silo: sandbox
  timeout:
test:
  username: sandbox_user
  password: sandbox
  host: http://10.0.0.173/
  silo: sandbox
  timeout:
production:
  username: sandbox_user
  password: sandbox
  host: http://10.0.0.173/
  silo: sandbox
  timeout:
