development:
  username: sandbox_user
  password: sandbox
  host: http://10.0.0.173/
  silo: sandbox
test:
  username: sandbox_user
  password: sandbox
  host: http://10.0.0.173/
  silo: sandbox
production:
  username: sandbox_user
  password: sandbox
  host: http://10.0.0.173/
  silo: sandbox
